# 基本設定（必要に応じて編集）

general:
  base_currency: JPY
  start_cash: 1_000_000  # 初期資金（JPY）
  timezone: UTC

data:
  # CSV入力の例。1時間足想定。
  # 列: timestamp,open,high,low,close,volume
  csv_path: data/USDJPY_1h.csv

strategy:
  name: momo_atr
  params:
    ema_fast: 10
    ema_slow: 50
    atr_window: 14
    atr_k_stop: 1.5  # 初期ストップのATR倍率（提案値）
    vol_filter_min_atr_pct: 0.02  # 例: 2%/100 の相対ATRでフィルタ（提案値）

risk:
  per_trade_risk_pct: 0.25  # 1トレードの口座リスク上限（%）
  daily_loss_stop_pct: 1.0   # 日次損失で停止（%）
  max_concurrent_positions: 1

backtest:
  slippage_pct: 0.0001  # 1bp相当
  fee_perc_roundturn: 0.0002  # 2bp相当（往復）
  tz: UTC

output:
  report_dir: out
