name: Changelog Lite

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Collect merged PRs
        id: prs
        run: |
          echo "PR_LIST<<EOF" >> $GITHUB_OUTPUT
          git log --merges --pretty=format:'%s (%h)%n' -n 20 | sed -n 's/^Merge pull request #\([0-9]*\) .*$/#\1/p' | while read pr; do
            echo "$pr"
          done >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Append to docs/CHANGELOG_LITE.md
        run: |
          FILE=docs/CHANGELOG_LITE.md
          echo "## $(date -u +'%Y-%m-%d')" >> $FILE
          if [ -n "${{ steps.prs.outputs.PR_LIST }}" ]; then
            echo "${{ steps.prs.outputs.PR_LIST }}" | while read pr; do
              [ -z "$pr" ] && continue
              echo "- Merged PR ${pr}" >> $FILE
            done
          else
            echo "- No merged PR detected in recent history" >> $FILE
          fi
          echo "" >> $FILE

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/CHANGELOG_LITE.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore(docs): update CHANGELOG_LITE [skip ci]"
          git push

