name: Release Drafter

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, edited, labeled, unlabeled, closed, reopened, synchronize]

jobs:
  update_release_draft:
    if: ${{ vars.CI_ALLOW == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
